-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 17:34:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dabom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dabom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dabom` DEFAULT CHARACTER SET utf8 ;
USE `dabom` ;

-- -----------------------------------------------------
-- Table `dabom`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`channel` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `score_sum` VARCHAR(45) NULL,
  `vote_people_count` VARCHAR(45) NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`image` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `saved_url` VARCHAR(50) NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`member` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `password` VARCHAR(50) NULL,
  `member_role` VARCHAR(20) NULL,
  `score_sum` BIGINT(20) NULL,
  `vote_people_count` BIGINT(20) NULL,
  `channel_idx` INT NOT NULL,
  `image_idx` INT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `channel_idx`, `image_idx`),
  INDEX `fk_member_channel1_idx` (`channel_idx` ASC) VISIBLE,
  INDEX `fk_member_image1_idx` (`image_idx` ASC) VISIBLE,
  CONSTRAINT `fk_member_channel1`
    FOREIGN KEY (`channel_idx`)
    REFERENCES `mydb`.`channel` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_image1`
    FOREIGN KEY (`image_idx`)
    REFERENCES `mydb`.`image` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`message` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(400) NULL,
  `message_type` VARCHAR(20) NULL,
  `post_user_idx` INT NULL,
  `send_user_idx` INT NULL,
  `member_idx` INT NOT NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `member_idx`),
  INDEX `fk_message_member1_idx` (`member_idx` ASC) VISIBLE,
  CONSTRAINT `fk_message_member1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`video` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `video_url` VARCHAR(50) NULL,
  `saved_url` VARCHAR(50) NULL,
  `title` VARCHAR(30) NULL,
  `content` VARCHAR(400) NULL,
  `view_count` BIGINT(20) NULL,
  `view_age_limt` VARCHAR(20) NULL,
  `channel_idx` INT NOT NULL,
  `image_idx` INT NOT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `channel_idx`, `image_idx`),
  INDEX `fk_video_channel1_idx` (`channel_idx` ASC) VISIBLE,
  INDEX `fk_video_image1_idx` (`image_idx` ASC) VISIBLE,
  CONSTRAINT `fk_video_channel1`
    FOREIGN KEY (`channel_idx`)
    REFERENCES `mydb`.`channel` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_image1`
    FOREIGN KEY (`image_idx`)
    REFERENCES `mydb`.`image` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`together`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`together` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NULL,
  `host_user_id` INT NULL,
  `video_idx` INT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `video_idx`),
  INDEX `fk_together_video1_idx` (`video_idx` ASC) VISIBLE,
  CONSTRAINT `fk_together_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`score` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `score` BIGINT(20) NULL,
  `video_idx` INT NOT NULL,
  `member_idx` INT NOT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `video_idx`, `member_idx`),
  INDEX `fk_score_video1_idx` (`video_idx` ASC) VISIBLE,
  INDEX `fk_score_member1_idx` (`member_idx` ASC) VISIBLE,
  CONSTRAINT `fk_score_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_member1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`category` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(20) NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`tage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`tage` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`message_has_together`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`message_has_together` (
  `message_idx` INT NOT NULL,
  `together_idx` INT NOT NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  `idx` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_message_has_together_together1_idx` (`together_idx` ASC) VISIBLE,
  INDEX `fk_message_has_together_message1_idx` (`message_idx` ASC) VISIBLE,
  PRIMARY KEY (`idx`),
  CONSTRAINT `fk_message_has_together_message1`
    FOREIGN KEY (`message_idx`)
    REFERENCES `mydb`.`message` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_has_together_together1`
    FOREIGN KEY (`together_idx`)
    REFERENCES `mydb`.`together` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`together_has_memeber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`together_has_memeber` (
  `together_idx` INT NOT NULL,
  `memeber_idx` INT NOT NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  `idx` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_together_has_memeber_memeber1_idx` (`memeber_idx` ASC) VISIBLE,
  INDEX `fk_together_has_memeber_together1_idx` (`together_idx` ASC) VISIBLE,
  PRIMARY KEY (`idx`),
  CONSTRAINT `fk_together_has_memeber_together1`
    FOREIGN KEY (`together_idx`)
    REFERENCES `mydb`.`together` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_together_has_memeber_memeber1`
    FOREIGN KEY (`memeber_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`member_has_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`member_has_video` (
  `member_idx` INT NOT NULL,
  `video_idx` INT NOT NULL,
  `video_saved_url` VARCHAR(50) NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  `idx` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_memeber_has_video_video1_idx` (`video_idx` ASC) VISIBLE,
  INDEX `fk_memeber_has_video_memeber1_idx` (`member_idx` ASC) VISIBLE,
  PRIMARY KEY (`idx`),
  CONSTRAINT `fk_memeber_has_video_memeber1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_memeber_has_video_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`video_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`video_has_category` (
  `video_idx` INT NOT NULL,
  `category_idx` INT NOT NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  `idx` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idx`),
  INDEX `fk_video_has_category_category1_idx` (`category_idx` ASC) VISIBLE,
  INDEX `fk_video_has_category_video1_idx` (`video_idx` ASC) VISIBLE,
  CONSTRAINT `fk_video_has_category_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_has_category_category1`
    FOREIGN KEY (`category_idx`)
    REFERENCES `mydb`.`category` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`post` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NULL,
  `context` LONGTEXT NULL,
  `image_idx` INT NOT NULL,
  `member_idx` INT NOT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `image_idx`, `member_idx`),
  INDEX `fk_post_image1_idx` (`image_idx` ASC) VISIBLE,
  INDEX `fk_post_member1_idx` (`member_idx` ASC) VISIBLE,
  CONSTRAINT `fk_post_image1`
    FOREIGN KEY (`image_idx`)
    REFERENCES `mydb`.`image` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_member1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`comment` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `context` LONGTEXT NOT NULL,
  `member_idx` INT NULL,
  `post_idx` INT NULL,
  `comment_idx` INT NULL,
  `video_idx` INT NULL,
  `host_id` INT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `member_idx`, `post_idx`, `comment_idx`, `video_idx`),
  INDEX `fk_comment_member1_idx` (`member_idx` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post_idx` ASC) VISIBLE,
  INDEX `fk_comment_comment1_idx` (`comment_idx` ASC) VISIBLE,
  INDEX `fk_comment_video1_idx` (`video_idx` ASC) VISIBLE,
  CONSTRAINT `fk_comment_member1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_idx`)
    REFERENCES `mydb`.`post` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_comment1`
    FOREIGN KEY (`comment_idx`)
    REFERENCES `mydb`.`comment` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`play_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`play_list` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `member_idx` INT NOT NULL,
  `title` VARCHAR(50) NULL,
  `create_at` DATETIME NULL DEFAULT now(),
  `update_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `member_idx`),
  INDEX `fk_view_list_member1_idx` (`member_idx` ASC) VISIBLE,
  CONSTRAINT `fk_view_list_member1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`play_list_has_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`play_list_has_video` (
  `play_list_idx` INT NOT NULL,
  `video_idx` INT NOT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  `idx` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idx`),
  INDEX `fk_view_list_has_video_video1_idx` (`video_idx` ASC) VISIBLE,
  INDEX `fk_view_list_has_video_view_list1_idx` (`play_list_idx` ASC) VISIBLE,
  CONSTRAINT `fk_view_list_has_video_view_list1`
    FOREIGN KEY (`play_list_idx`)
    REFERENCES `mydb`.`play_list` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_view_list_has_video_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`report` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `member_idx` INT NULL,
  `comment_idx` INT NULL,
  `post_idx` INT NULL,
  `score_idx` INT NULL,
  `message_idx` INT NULL,
  `video_idx` INT NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`, `member_idx`, `comment_idx`, `post_idx`, `score_idx`, `message_idx`, `video_idx`),
  INDEX `fk_report_member1_idx` (`member_idx` ASC) VISIBLE,
  INDEX `fk_report_comment1_idx` (`comment_idx` ASC) VISIBLE,
  INDEX `fk_report_post1_idx` (`post_idx` ASC) VISIBLE,
  INDEX `fk_report_score1_idx` (`score_idx` ASC) VISIBLE,
  INDEX `fk_report_message1_idx` (`message_idx` ASC) VISIBLE,
  INDEX `fk_report_video1_idx` (`video_idx` ASC) VISIBLE,
  UNIQUE INDEX `member_idx_UNIQUE` (`member_idx` ASC) VISIBLE,
  UNIQUE INDEX `comment_idx_UNIQUE` (`comment_idx` ASC) VISIBLE,
  UNIQUE INDEX `post_idx_UNIQUE` (`post_idx` ASC) VISIBLE,
  UNIQUE INDEX `score_idx_UNIQUE` (`score_idx` ASC) VISIBLE,
  UNIQUE INDEX `message_idx_UNIQUE` (`message_idx` ASC) VISIBLE,
  UNIQUE INDEX `video_idx_UNIQUE` (`video_idx` ASC) VISIBLE,
  CONSTRAINT `fk_report_member1`
    FOREIGN KEY (`member_idx`)
    REFERENCES `mydb`.`member` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_comment1`
    FOREIGN KEY (`comment_idx`)
    REFERENCES `mydb`.`comment` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_post1`
    FOREIGN KEY (`post_idx`)
    REFERENCES `mydb`.`post` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_score1`
    FOREIGN KEY (`score_idx`)
    REFERENCES `mydb`.`score` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_message1`
    FOREIGN KEY (`message_idx`)
    REFERENCES `mydb`.`message` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_video1`
    FOREIGN KEY (`video_idx`)
    REFERENCES `mydb`.`video` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dabom`.`score_has_tage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dabom`.`score_has_tage` (
  `score_idx` INT NOT NULL,
  `tage_idx` INT NOT NULL,
  `idx` INT NOT NULL AUTO_INCREMENT,
  `score_has_tagecol` VARCHAR(45) NULL,
  `update_at` DATETIME NULL DEFAULT now(),
  `create_at` DATETIME NULL DEFAULT now(),
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idx`),
  INDEX `fk_score_has_tage_tage1_idx` (`tage_idx` ASC) VISIBLE,
  INDEX `fk_score_has_tage_score1_idx` (`score_idx` ASC) VISIBLE,
  CONSTRAINT `fk_score_has_tage_score1`
    FOREIGN KEY (`score_idx`)
    REFERENCES `mydb`.`score` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_has_tage_tage1`
    FOREIGN KEY (`tage_idx`)
    REFERENCES `mydb`.`tage` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;